.. |tenantname| replace:: <tenant-name>
.. |site-name| replace:: <foo>
.. |latitude| replace:: <latitude>
.. |longitude| replace:: <longitude>
.. |address| replace:: <address>
.. |jumpbox-hostname| replace:: <jumpbox-hostname>
.. |jumpbox-username| replace:: <username>
.. |github-username| replace:: <github-username>
.. |github-user-email| replace:: <email@example.com>
.. |github-user-name| replace:: <FirstName LastName>
