.. |tenantname| replace:: <tenant-name>
.. |sitename| replace:: <site-name>
.. |address| replace:: <address>
.. |latitude| replace:: <latitude>
.. |longitude| replace:: <longitude>
.. |cenodename| replace:: <ce-hostname>
.. |cenodeaddress| replace:: <ce-IP-address>
.. |cenodeport| replace:: <ce-node-port>
.. |workstationhostname| replace:: <workstation-hostname>
.. |workstationusername| replace:: ubuntu
.. |workstationsshport| replace:: <22>
.. |githuborgname| 
.. |githubrepo| replace:: f5-xc-iac
.. |github_repo| replace:: f5-xc-iac
.. |githubrepobranch| replace:: main
.. |github_version| replace:: main
.. |githubusername| replace:: <github-username>
.. |githubuseremail| replace:: <email@example.com>
.. |githubusername| replace:: <FirstName LastName>
.. |github_user| replace:: <github-org-name>
