.. |tenantname| replace:: <tenant-name>
.. |sitename| replace:: <foo>
.. |latitude| replace:: <latitude>
.. |longitude| replace:: <longitude>
.. |address| replace:: <address>
.. |workstationhostname| replace:: <workstation-hostname>
.. |workstationusername| replace:: <username>
.. |workstationsshport| replace:: <22>
.. |githubusername| replace:: <github-username>
.. |githubuseremail| replace:: <email@example.com>
.. |githubusername| replace:: <FirstName LastName>
